server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-eureka: true # 表示向注册中心注册自己（默认为true）
    fetch-registry: true # 是否从EurekaServer抓取已有的注册信息,单节点无所谓,集群必须设置为true才能配合ribbon使用负载均衡（默认为true）
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
#      defaultZone: http://localhost:7001/eureka/
    registry-fetch-interval-seconds: 5 # eureka client间隔多久去拉取服务注册信息，默认为30秒 
  instance:
    lease-renewal-interval-in-seconds: 5 # eureka client发送心跳给server端的频率，默认为30秒 

ribbon:
  eager-load:
    # 开启Ribbon的饥饿加载模式
    enabled: true
    # 开启Ribbon的饥饿加载模式
  clients: cloud-payment-service1,cloud-payment-service2
