server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com #eureka服务端实例名称
  client:
    register-with-eureka: false #表示不向注册中心注册自己（默认为true）
    fetch-registry: false #false表示自己就是注册中心，我的职责就是维护服务实例,并不区检索服务（默认为true）
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
      # 集群指向其他eureka
      #defaultZone: http://eureka7002.com:7002/eureka/